stages:
    - test
    - containerize
    - verify
    - release

include:
    - remote: https://gitlab.com/TIBHannover/gitlab-ci-templates/raw/master/templates/Docker.gitlab-ci.yml
    - remote: https://gitlab.com/TIBHannover/gitlab-ci-templates/raw/master/templates/Docker-Release.gitlab-ci.yml
    - template: Security/Container-Scanning.gitlab-ci.yml
    - template: Dependency-Scanning.gitlab-ci.yml

jest:
    image: node:lts-buster
    stage: test
    needs: [] # speed up, doesn't depend on other jobs
    script:
        - cp default.env .env
        - npm install
        - npm run test:ci
    artifacts:
        when: always
        reports:
            junit:
                - junit.xml

container_scanning:
    stage: verify
    variables:
        CS_ANALYZER_IMAGE: registry.gitlab.com/security-products/container-scanning/grype:4
        # Change image name to match our repository naming convention
        CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE

dependency_scanning:
    stage: verify
